export const jokesObj = {
	error: false,
	amount: 10,
	jokes: [
		{
			category: 'Programming',
			type: 'single',
			joke: 'Saying that Java is nice because it works on every OS is like saying that anal sex is nice because it works on every gender.',
			flags: {
				nsfw: true,
				religious: false,
				political: false,
				racist: false,
				sexist: false,
				explicit: true,
			},
			id: 30,
			safe: false,
			lang: 'en',
		},
		{
			category: 'Programming',
			type: 'twopart',
			setup: 'Why do programmers prefer using the dark mode?',
			delivery: 'Because light attracts bugs.',
			flags: {
				nsfw: false,
				religious: false,
				political: false,
				racist: false,
				sexist: false,
				explicit: false,
			},
			id: 232,
			safe: true,
			lang: 'en',
		},
		{
			category: 'Programming',
			type: 'twopart',
			setup: 'Hey, wanna hear a joke?',
			delivery: 'Parsing HTML with regex.',
			flags: {
				nsfw: false,
				religious: false,
				political: false,
				racist: false,
				sexist: false,
				explicit: false,
			},
			id: 10,
			safe: true,
			lang: 'en',
		},
		{
			category: 'Programming',
			type: 'twopart',
			setup: 'Why is 6 afraid of 7 in hexadecimal Canada?',
			delivery: 'Because 7 8 9 A?',
			flags: {
				nsfw: false,
				religious: false,
				political: false,
				racist: false,
				sexist: false,
				explicit: false,
			},
			id: 7,
			safe: true,
			lang: 'en',
		},
		{
			category: 'Programming',
			type: 'single',
			joke: 'Java and C were telling jokes. It was C\'s turn, so he writes something on the wall, points to it and says "Do you get the reference?" But Java didn\'t.',
			flags: {
				nsfw: false,
				religious: false,
				political: false,
				racist: false,
				sexist: false,
				explicit: false,
			},
			id: 4,
			safe: true,
			lang: 'en',
		},
		{
			category: 'Programming',
			type: 'single',
			joke: 'Today I learned that changing random stuff until your program works is "hacky" and a "bad coding practice" but if you do it fast enough it\'s "Machine Learning" and pays 4x your current salary.',
			flags: {
				nsfw: false,
				religious: false,
				political: false,
				racist: false,
				sexist: false,
				explicit: false,
			},
			id: 33,
			safe: true,
			lang: 'en',
		},
		{
			category: 'Programming',
			type: 'twopart',
			setup: 'Why did the programmer quit his job?',
			delivery: "Because he didn't get arrays.",
			flags: {
				nsfw: false,
				religious: false,
				political: false,
				racist: false,
				sexist: false,
				explicit: false,
			},
			id: 16,
			safe: true,
			lang: 'en',
		},
		{
			category: 'Programming',
			type: 'single',
			joke: 'Debugging: Removing the needles from the haystack.',
			flags: {
				nsfw: false,
				religious: false,
				political: false,
				racist: false,
				sexist: false,
				explicit: false,
			},
			id: 40,
			safe: true,
			lang: 'en',
		},
		{
			category: 'Programming',
			type: 'twopart',
			setup: 'What do you call a group of 8 Hobbits?',
			delivery: 'A Hobbyte.',
			flags: {
				nsfw: false,
				religious: false,
				political: false,
				racist: false,
				sexist: false,
				explicit: false,
			},
			id: 29,
			safe: true,
			lang: 'en',
		},
		{
			category: 'Programming',
			type: 'single',
			joke: 'Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.',
			flags: {
				nsfw: false,
				religious: false,
				political: false,
				racist: false,
				sexist: false,
				explicit: false,
			},
			id: 37,
			safe: true,
			lang: 'en',
		},
	],
};
